Dev january
anthonyLuttrell/StatsBot pull request #25
Opened 2023-12-22 20:37 UTC by bunnysapple

First draft of infinite scroll

2023-12-22 21:40 UTC, anthonyLuttrell requested changes
Just some questions from me and some minor changes.

2023-12-22 21:40 UTC, anthonyLuttrell commented on web/js/main.js
> +        box.removeEventListener('scroll', scrollEvent);
I'm not too sure what this is doing, can you try to better explain this?

2023-12-22 21:40 UTC, anthonyLuttrell commented on web/js/main.js
> +                    break;
Does this mean we've scrolled all the way to the end? If so, why remove the listener? What happens if you don't remove it?

2023-12-22 21:40 UTC, anthonyLuttrell commented on web/js/main.js
> +    //for (const user of totalsArray) {
safe to remove

2023-12-22 21:40 UTC, anthonyLuttrell commented on web/js/main.js
>          // TODO this can all be refactored into smaller nested functions
safe to remove

2023-12-22 21:40 UTC, anthonyLuttrell commented on web/js/main.js
> +// made this bit into a function so that it can be used in multiple places without needing to rewrite all of it
go ahead and add a proper JSDoc formatted function description. See here: https://google.github.io/styleguide/jsguide.html#jsdoc

We don't need to follow the 80 character column width, 120 is fine. 

We need to eventually do this to all of the other functions that don't have it as well.

2023-12-22 22:14 UTC, bunnysapple commented on web/js/main.js
> +        box.removeEventListener('scroll', scrollEvent);
When you select a sub for the first time, it adds an event Listener to the select tag so that, when you select a different option, the existing scroll event Listener is removed. Further down, you can see that I add the scroll event listener back.

By this, I basically wanted to reset the scroll event listener every time you change subs. When you don't reset the scroll event listener and you select a different sub, the information first 50 rows generated would change, but the new rows generated when you scroll down would have the same information as before you selected the new sub.

2023-12-22 22:16 UTC, bunnysapple commented on web/js/main.js
> +                    break;
Yes, it means we have reached the end. If you don't remove the event listener here, new, empty rows will continue to be generated and error messages pop up in the console because there's no data being passed through other functions that are activated.

2023-12-23 17:46 UTC, anthonyLuttrell approved these changes

2023-12-23 17:47 UTC, merged